version: "3.9"

services:
  smtp-relay:
    image: instantlinux/postfix:latest
    container_name: smtp-relay
    restart: unless-stopped
    environment:
      RELAYHOST: "[smtp.mailbox.org]:587"
      RELAY_USER: "${MAILBOX_USER}"
      RELAY_PASSWORD: "${MAILBOX_PASS}"
      POSTFIX_myhostname: "${SMTP_RELAY_HOSTNAME:-relay.home}"
      POSTFIX_mynetworks: "${SMTP_RELAY_NETWORKS:-172.18.0.0/16 10.42.42.0/24}"
      TLS_LEVEL: "may"
      SMTP_TLS_SECURITY_LEVEL: "encrypt"
      SMTP_TLS_CA_FILE: "/etc/ssl/certs/ca-certificates.crt"
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
    networks:
      - proxy
    ports:
      - "25:25"
networks:
  proxy:
    external: true
    name: proxy
